linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - dupl
    - gocritic

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - gocyclo

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: package-comments
      - name: exported
      - name: var-naming
      - name: var-declaration
      - name: struct-tag
      - name: receiver-naming
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: comments
      - name: dot-imports
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: range
      - name: range-val-in-closure
      - name: range-val-address
      - name: unexported-return
      - name: time-naming
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: exported
      - name: string-of-int
      - name: string-format
      - name: early-return
      - name: unhandled-error
      - name: defer
      - name: receiver-naming
      - name: unexported-naming
      - name: errorf
      - name: error-naming
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style 